### ISSUE TITLE
Odd formatting for example list

### ISSUE THREAD

**Issue by chrisalleng** [FreakyDug/r2-d7#15]
In Discord, when printing this list:
https://raithos.github.io/?f=Rebel%20Alliance&d=v8ZsZ200Z43XWWW52W40WWWY73XWWWWWY4XWWWW142&sn=Unnamed%20Squadron&obs=

prints as this, with an extra ')' after Nien Nunb:
![image](https://user-images.githubusercontent.com/3527305/65396145-1c754080-dd71-11e9-9f66-dfaf6de4f091.png)

but in slack, prints correctly:
![image](https://user-images.githubusercontent.com/3527305/65396149-29922f80-dd71-11e9-8e96-3ae009c7460e.png)

**Comment by FreakyDug** [comment]
That's a weird one, thanks for reporting it. I'll do some experiementing and see if I can work out why that link specifically is breaking.

**Comment by FreakyDug** [comment]
Turns out discord doesn't like having double )) in a url, so I url escaped the card name in the wiki link. It's working properly now.
