### ISSUE TITLE
I think Travis is dead

### ISSUE THREAD

**Issue by danrs** [FreakyDug/r2-d7#39]
Looking at my new PR (and the one raised by Apollonaut), it looks like travis integration has gone? I assume this occurred when travis migrated to their new domain or whatever it was that they did recently. It looks like this might also have killed our heroku auto-deploy pipeline.

**Comment by FreakyDug** [comment]
Hmm, I thought I'd done the thing for the domain move. I'll fix it or find a replacement this weekend. 🙂

**Comment by danrs** [comment]
How did you go with finding a fix? I noticed that Apollo's change got deployed, but CI and automated deployment still seems to be down

**Comment by danrs** [comment]
Or maybe I'm crazy, I'm not seeing automated tests but it looks like deployments are actually going through

**Comment by FreakyDug** [comment]
I replaced travis with circleci, so the tests should get run on PRs now. If it's not working on new PRs, let me know.
I didn't get the emoji upload working but will try and find some time to take another stab at it.

**Comment by danrs** [comment]
Thanks for setting CI back up again. I'll close this issue and raise a new PR to fix the failing tests. Apollo, you'll want to rebase your open PRs on the main branch once the test fix merges in so that they start passing tests
