### ISSUE TITLE
Change parsing method for LBN "Print URL" links

### ISSUE THREAD

**Issue by SogeMoge** [FreakyDug/r2-d7#62]
R2-D7 should remove ”print” from "Print URL" address created in Launch Bay next. (When user pastes list url in discord channel)
`https://launchbaynext.app/print?lbx` change to `https://launchbaynext.app/?lbx`

This way other users can open list from embedded list view in editable form in launchbay.app

Source(not editable): https://launchbaynext.app/print?lbx='New%20Squadron'.20.5.0.l52.415.l18.924r.l1.247r.l5.579rr.l70.624.l14.297.299r.l1.240.233rr.l49.399.l3.256r.l14.297rr.l49.452.l6.266rr.l49.454r

Changed address(editable): https://launchbaynext.app/?lbx='New%20Squadron'.20.5.0.l52.415.l18.924r.l1.247r.l5.579rr.l70.624.l14.297.299r.l1.240.233rr.l49.399.l3.256r.l14.297rr.l49.452.l6.266rr.l49.454r

**Comment by SogeMoge** [comment]
This was proposed by André himself

**Comment by danrs** [comment]
Fixed in #63
