### ISSUE TITLE
adding r2-d7 to a new workspace

### ISSUE THREAD

**Issue by rkukuchka** [FreakyDug/r2-d7#8]
hello, 
I've created a regional workspace for my local scene and was hoping to use r2-d7. I can chat directly to it, and get results, but it's not working in rooms

**Comment by FreakyDug** [comment]
Hi,

Have you invited the bot user into the channels you're trying to use it in?

**Comment by FreakyDug** [comment]
Spoke to @rkukuchka on slack, he had the wrong syntax for invoking the bot.
